apiVersion: v1
kind: Service
metadata:
  name: mywebserver-service
spec:
  type: NodePort
  selector:
    app: mywebserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Optionally specify a nodePort or let Kubernetes assign one

